blank_issues_enabled: false

issue_template:
  - name: "ğŸ Relatar um Bug"
    about: "Reporte um problema encontrado no sistema"
    filename: "bug_report.md"
  - name: "ğŸ§© Ã‰pico"
    about: "Agrupe issues relacionadas a um grande objetivo ou funcionalidade"
    filename: "epic.md"
  - name: "ğŸ§© Tarefa"
    about: "Descrever uma tarefa tÃ©cnica, funcional ou de design"
    filename: "task.md"
